#!/usr/bin/env bash

if [[ -z "$SAGE_LOCAL" ]]; then
    echo >&2 "SAGE_LOCAL undefined - exiting..."
    echo >&2 "Maybe run 'sage -sh'?"
    exit 1
fi

if [[ "$SAGE64" = yes ]]; then
    if [[ -z $CFLAG64 ]]; then
        CFLAG64=-m64
    fi
    CFLAGS="$CFLAGS $CFLAG64"
    CXXFLAGS="$CXXFLAGS $CFLAG64"
fi 

if [ "$SAGE_DEBUG" == "yes" ] ; then
    export CFLAGS="$CFLAGS -O0 -g"
    export CXXFLAGS="$CXXFLAGS -O0 -g"
fi

echo "Configuring libXon..."
cd src
./configure --disable-static CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" \
    --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib"
if [[ $? -ne 0 ]]; then
    echo >&2 "Error configuring libXon."
    exit 1
fi

echo "Building libXon..."
make
if [[ $? -ne 0 ]]; then
    echo >&2 "Error building libXon."
    exit 1
fi

echo "Installing libXon..."
make install
if [[ $? -ne 0 ]]; then
    echo >&2 "Error installing libXon."
    exit 1
fi

